//
//  Turno.swift
//
//  File Generated by vicentesiis on 09/16/2018.
//  Using model_gen.py
//

import ObjectMapper

class Turno: Mappable {

	var idTurno: Int!
	var usuario: Any!
	var turno: String!
	var enFila: Bool!

	init() {}

	required init?(map: Map){}

	func mapping(map: Map) {
		idTurno <- map["idTurno"]
		usuario <- map["usuario"]
		turno <- map["turno"]
		enFila <- map["enFila"]
	}
}

